server:
  port: 8081

spring:
  application:
    name: order-service

  data:
    mongodb:
      uri: mongodb+srv://iharikrishna180:2ulfk34gC8d7sVHr@hungersaviour.toiwnn1.mongodb.net/?retryWrites=true&w=majority
      database: orders
    #      uuid-representation: STANDARD
  kafka:
    consumer:
      bootstrap-servers:
          - "localhost:19092"
          - "localhost:29092"
          - "localhost:39092"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserialize


